# Generated by Django 4.2 on 2023-05-04 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 1, 39, 54, 916852)),
        ),
    ]
