# Generated by Django 4.2 on 2023-05-04 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0002_alter_trending_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
